import { createTRPCRouter } from "./index";
import {
  createDojoStyleProcedure,
  createPageProcedure,
  createSocialPostProcedure,
  createSocialReplyProcedure,
  createTagProcedure,
  createUserProcedure,
  deletePageProcedure,
  deleteTagProcedure,
  getNotificationsProcedure,
  getPageProcedure,
  getPagesProcedure,
  getSocialFeedProcedure,
  getSocialPostByIdProcedure,
  getSocialProfileProcedure,
  getTagsProcedure,
  getTrainingDatesMonthProcedure,
  getTrainingStatsProcedure,
  getUnreadNotificationCountProcedure,
  getUnreadNotificationPostIdsProcedure,
  getUserBasicInfoProcedure,
  healthProcedure,
  honoBridgeTodoProcedure,
  initializeUserTagsProcedure,
  markNotificationsReadProcedure,
  removeSocialPostProcedure,
  removeSocialReplyProcedure,
  removeTrainingDateAttendanceProcedure,
  reportPostProcedure,
  reportReplyProcedure,
  searchDojoStylesProcedure,
  searchSocialPostsProcedure,
  toggleFavoriteProcedure,
  toggleReplyFavoriteProcedure,
  updatePageProcedure,
  updateSocialPostProcedure,
  updateSocialReplyProcedure,
  updateTagOrderProcedure,
  updateUserBasicInfoProcedure,
  upsertTrainingDateAttendanceProcedure,
} from "./procedures";

export const appRouter = createTRPCRouter({
  health: healthProcedure,
  // TODO: Hono API 連携の手続きはここに追加していく
  honoBridgeTodo: honoBridgeTodoProcedure,
  pages: createTRPCRouter({
    getList: getPagesProcedure,
    getById: getPageProcedure,
    create: createPageProcedure,
    update: updatePageProcedure,
    remove: deletePageProcedure,
  }),
  stats: createTRPCRouter({
    get: getTrainingStatsProcedure,
  }),
  trainingDates: createTRPCRouter({
    getMonth: getTrainingDatesMonthProcedure,
    upsertAttendance: upsertTrainingDateAttendanceProcedure,
    removeAttendance: removeTrainingDateAttendanceProcedure,
  }),
  tags: createTRPCRouter({
    getList: getTagsProcedure,
    create: createTagProcedure,
    remove: deleteTagProcedure,
    updateOrder: updateTagOrderProcedure,
    initializeForUser: initializeUserTagsProcedure,
  }),
  dojoStyles: createTRPCRouter({
    search: searchDojoStylesProcedure,
    create: createDojoStyleProcedure,
  }),
  users: createTRPCRouter({
    getBasicInfo: getUserBasicInfoProcedure,
    updateBasicInfo: updateUserBasicInfoProcedure,
    create: createUserProcedure,
  }),
  socialPosts: createTRPCRouter({
    getFeed: getSocialFeedProcedure,
    getById: getSocialPostByIdProcedure,
    create: createSocialPostProcedure,
    update: updateSocialPostProcedure,
    remove: removeSocialPostProcedure,
    toggleFavorite: toggleFavoriteProcedure,
    report: reportPostProcedure,
  }),
  socialReplies: createTRPCRouter({
    create: createSocialReplyProcedure,
    update: updateSocialReplyProcedure,
    remove: removeSocialReplyProcedure,
    report: reportReplyProcedure,
    toggleFavorite: toggleReplyFavoriteProcedure,
  }),
  socialSearch: createTRPCRouter({
    search: searchSocialPostsProcedure,
  }),
  socialProfile: createTRPCRouter({
    get: getSocialProfileProcedure,
  }),
  notifications: createTRPCRouter({
    getList: getNotificationsProcedure,
    markAsRead: markNotificationsReadProcedure,
    getUnreadCount: getUnreadNotificationCountProcedure,
    getUnreadPostIds: getUnreadNotificationPostIdsProcedure,
  }),
});

export type AppRouter = typeof appRouter;
