export type TagLanguage = "ja" | "en";

export const DEFAULT_CATEGORIES = [
  { name: "取り", slug: "tori", sort_order: 1 },
  { name: "受け", slug: "uke", sort_order: 2 },
  { name: "技", slug: "waza", sort_order: 3 },
] as const;

export const MAX_CATEGORIES = 5;

export const INITIAL_USER_TAGS: Record<
  TagLanguage,
  readonly { category: string; name: string }[]
> = {
  ja: [
    { category: "取り", name: "立技" },
    { category: "取り", name: "坐技" },
    { category: "取り", name: "半身半立" },
    { category: "受け", name: "相半身" },
    { category: "受け", name: "逆半身" },
    { category: "受け", name: "後ろ" },
    { category: "受け", name: "片手取り" },
    { category: "受け", name: "諸手取り" },
    { category: "受け", name: "両手取り" },
    { category: "受け", name: "肩取り" },
    { category: "受け", name: "正面打ち" },
    { category: "受け", name: "横面打ち" },
    { category: "受け", name: "突き" },
    { category: "受け", name: "肩取り面打ち" },
    { category: "技", name: "一教" },
    { category: "技", name: "二教" },
    { category: "技", name: "三教" },
    { category: "技", name: "四教" },
    { category: "技", name: "五教" },
    { category: "技", name: "入り身投げ" },
    { category: "技", name: "四方投げ" },
    { category: "技", name: "小手返し" },
    { category: "技", name: "回転投げ" },
    { category: "技", name: "腰投げ" },
    { category: "技", name: "天秤投げ" },
    { category: "技", name: "呼吸法" },
  ],
  en: [
    { category: "取り", name: "Standing" },
    { category: "取り", name: "Seated" },
    { category: "取り", name: "Half-standing" },
    { category: "受け", name: "Ai-hanmi" },
    { category: "受け", name: "Gyaku-hanmi" },
    { category: "受け", name: "Ushiro" },
    { category: "受け", name: "Katate-dori" },
    { category: "受け", name: "Morote-dori" },
    { category: "受け", name: "Ryote-dori" },
    { category: "受け", name: "Kata-dori" },
    { category: "受け", name: "Shomen-uchi" },
    { category: "受け", name: "Yokomen-uchi" },
    { category: "受け", name: "Tsuki" },
    { category: "受け", name: "Kata-dori men-uchi" },
    { category: "技", name: "Ikkyo" },
    { category: "技", name: "Nikyo" },
    { category: "技", name: "Sankyo" },
    { category: "技", name: "Yonkyo" },
    { category: "技", name: "Gokyo" },
    { category: "技", name: "Irimi-nage" },
    { category: "技", name: "Shiho-nage" },
    { category: "技", name: "Kote-gaeshi" },
    { category: "技", name: "Kaiten-nage" },
    { category: "技", name: "Koshi-nage" },
    { category: "技", name: "Tenbin-nage" },
    { category: "技", name: "Kokyu-ho" },
  ],
} as const;
