name: Backend CI

on:
  workflow_call:
    workflow_call:
      secrets:
        SUPABASE_URL:
          required: true
        SUPABASE_SERVICE_ROLE_KEY:
          required: true
    secrets:
      DATABASE_URL:
        required: true
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: pnpm install --frozen-lockfile

      - name: Build Backend
        working-directory: ./backend
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: pnpm build

      # - name: Run Backend Tests
      #   run: pnpm test
      #   working-directory: ./backend
