name: Daily Main CI

on:
  # 毎日、日本時間の午前8時に実行
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main_ci.yml"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/main_ci.yml"

jobs:
  call-frontend-ci:
    name: Call Frontend CI
    uses: ./.github/workflows/frontend_ci.yml
    secrets:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
      CLOUDFRONT_DOMAIN: ${{ secrets.CLOUDFRONT_DOMAIN }}
      NEXT_PUBLIC_CLOUDFRONT_DOMAIN: ${{ secrets.NEXT_PUBLIC_CLOUDFRONT_DOMAIN }}

  call-backend-ci:
    name: Call Backend CI
    uses: ./.github/workflows/backend_ci.yml
    secrets:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
